In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

Pandas DATA STRUCTURE

In [2]:
obj = pd.Series([1,2,3,4])

In [3]:
type(obj)

pandas.core.series.Series

In [4]:
obj

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
obj.values

array([1, 2, 3, 4])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

Series with modified index or LABEL

In [7]:
obj2 = pd.Series([4,7,-5,3],index=[0,0,0,0])

In [8]:
obj2

0    4
0    7
0   -5
0    3
dtype: int64

In [9]:
obj2.index

Int64Index([0, 0, 0, 0], dtype='int64')

In [10]:
obj2[0]

0    4
0    7
0   -5
0    3
dtype: int64

In [11]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [12]:
obj3 = pd.Series(sdata)

In [13]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [15]:
obj4 = pd.Series(sdata, index=states)

In [16]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isnull(obj4).sum()

1

#### DATAFRAMES

In [18]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [19]:
obj2.values

array([ 4,  7, -5,  3])

In [20]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [21]:
obj2[['d','b']]

d    4
b    7
dtype: int64

In [22]:
obj2>0

d     True
b     True
a    False
c     True
dtype: bool

In [23]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [24]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

- think of a series as key(labels) - vvalue pairs

In [25]:
'b' in obj

False

In [26]:
'b' in obj2

True

In [27]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(obj3)

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [30]:
obj4 = pd.Series(sdata,index=states)

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
obj4[obj4.isnull()]

California   NaN
dtype: float64

In [34]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

 - name attribute of Series object and index

In [35]:
obj4.name = 'pop'

In [36]:
obj4.name

'pop'

In [37]:
obj4.index.name = 'state'

In [38]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: pop, dtype: float64

#### DataFrames

In [39]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [40]:
frame = pd.DataFrame(data)

In [41]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

- you can rearrange cols when loading in

In [42]:
pd.DataFrame(data,columns=['year','state','pop','debt'])

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [43]:
# a column in a DF can retrieved like a series
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [44]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],\
    index=['one', 'two', 'three', 'four','five', 'six'])

In [45]:
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [46]:
# Modifying cols
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [50]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [51]:
frame2['debt'] = val

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [53]:
frame2['eastern'] = frame2['state']=='Ohio'

In [54]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [55]:
del frame2['eastern']

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
# NESTED DICT OF DICT

pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [58]:
# OUTER DICT keys = COLS indices
# INNVER DICT keys = row indices

frame3 = pd.DataFrame(pop)

In [59]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [60]:
# YOU CAN TRANSPOSE
frame3.T 

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [61]:
# YOU CAN SET NAME FOR INDEX AND COLS
frame3.index.name = 'year'
frame3.columns.name = 'State'

In [62]:
frame3

State  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [63]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [64]:
type(frame3.values)

numpy.ndarray

In [65]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

#### Index Objects

In [66]:
# you can create index
labels = pd.Index(np.arange(3))

In [67]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [68]:
obj2 = pd.Series([0,1,2],index=labels)

In [69]:
obj2

0    0
1    1
2    2
dtype: int64

#### Essential Functionality

In [71]:
# Function Application and Mapping
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=\
    ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [72]:
frame

b         d         e
Utah    0.067517 -0.842397  1.921325
Ohio   -0.121243 -0.104277 -0.262177
Texas   0.799229  0.927891  0.840415
Oregon -0.119963 -1.351640  0.024835

In [73]:
np.abs(frame)

b         d         e
Utah    0.067517  0.842397  1.921325
Ohio    0.121243  0.104277  0.262177
Texas   0.799229  0.927891  0.840415
Oregon  0.119963  1.351640  0.024835

In [75]:
# applying a function in series (default)
f = lambda x: x.max() - x.min()
frame.apply(f,axis=0) # be deafult x is a series

b    0.920472
d    2.279532
e    2.183502
dtype: float64

In [76]:
# to do row-wise set axis to 1
frame.apply(f,axis=1)

Utah      2.763721
Ohio      0.157900
Texas     0.128663
Oregon    1.376476
dtype: float64

In [77]:
# apply can return series with multiple values
# finding min, max of each columns
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])


frame.apply(f)

b         d         e
min -0.121243 -1.351640 -0.262177
max  0.799229  0.927891  1.921325

In [78]:
# for element wise op use applymap
format = lambda x: '%.2f' %x 
frame.applymap(format)

b      d      e
Utah     0.07  -0.84   1.92
Ohio    -0.12  -0.10  -0.26
Texas    0.80   0.93   0.84
Oregon  -0.12  -1.35   0.02

Sorting and Ranking

In [79]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [80]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [81]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [82]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'],\
    columns=['d', 'a', 'b', 'c'])

In [83]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [84]:
# sort index by columns
frame.sort_index(axis=0)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [85]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [88]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [87]:
# sort a series by its values
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [89]:
# remember missing values will go end of the list
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [90]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [91]:
# sort by a column
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [92]:
# notice the index has been rearranged too

In [93]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [94]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [95]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [96]:
# Axes indexes with Duplicate Label
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [97]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [98]:
obj.index.is_unique

False

5.3 Summarizing and Computing Descriptive Statistics

In [99]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],\
    index=['a', 'b', 'c', 'd'],\
        columns=['one', 'two'])

In [100]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [101]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [102]:
# by default gives you column wise sum

In [103]:
# you can get row wise sum by setting axis 1
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [104]:
# some methods returns index
df.idxmax(axis=0)

one    b
two    d
dtype: object

In [105]:
# some methods are accumulative
df.cumsum() 

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [109]:
df.mad()

one    2.677778
two    1.600000
dtype: float64

In [110]:
# Correlation and Covariance

In [117]:
# Unique values, value counts and Membership

In [118]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [119]:
# get the unique values from a series
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [120]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [121]:
# Masking by membership
mask = obj.isin(['b','c'])

In [122]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object