In [1]:
import numpy as np

### 1. Vectors, the 1D Arrays

In [2]:
# Numpy array initialization
a = np.array([1,2,3])
a.shape

(3,)

In [3]:
b = np.zeros(3,int)

In [4]:
# to match the shape and data type use _like

c = np.zeros_like(a)

In [5]:
c

array([0, 0, 0])

In [6]:
c.shape

(3,)

In [7]:
np.full((2,3),-10)

array([[-10, -10, -10],
       [-10, -10, -10]])

In [8]:
# init with monotonic sequence
# np.arange(start,stop,step)
np.arange(6) # stop

array([0, 1, 2, 3, 4, 5])

In [9]:
np.arange(2,6)

array([2, 3, 4, 5])

In [10]:
np.arange(1,6,2)

array([1, 3, 5])

In [11]:
# np.linspace(start,stop,num)
np.linspace(0,0.5,6)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

In [12]:
# if you want to specify datatypes use .astype
np.arange(1,5).astype(float)

array([1., 2., 3., 4.])

In [13]:
# or you can do it like this
np.arange(3.)

array([0., 1., 2.])

In [14]:
# Try not to use np.arange for generating floats though
np.arange(0.5,0.8,0.1) #???????

array([0.5, 0.6, 0.7, 0.8])

In [15]:
np.arange(0.5,0.75,.1)

array([0.5, 0.6, 0.7])

In [16]:
#### Generating Random numbers
# Uniform
np.random.randint(0,10,(2,3)) # (start,stop,num)

array([[5, 1, 8],
       [5, 1, 6]])

In [17]:
np.random.rand(3)

array([0.42034689, 0.43569682, 0.88521558])

In [18]:
np.random.normal(5,2,4) # (mean,std,size)

array([8.00000442, 6.39607718, 4.26588361, 3.27007513])

#### Vector Indexing

In [19]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [20]:
a[1]

2

In [21]:
a[2:4]

array([3, 4])

In [22]:
a[-2:]

array([4, 5])

In [23]:
a[::2]

array([1, 3, 5])

In [24]:
# Fancy indexing
a[[1,3,4]]

array([2, 4, 5])

In [25]:
a[2:4]=0

In [26]:
a

array([1, 2, 0, 0, 5])

In [27]:
# array copying
d = a.copy()

In [28]:
d

array([1, 2, 0, 0, 5])

In [29]:
### Boolean Indexing

In [30]:
a = np.array([1,2,3,4,5,6,5,4,3,2,1])
a>5

array([False, False, False, False, False,  True, False, False, False,
       False, False])

In [31]:
a[a>5]

array([6])

In [32]:
# two useful functions
np.any(a>5)

True

In [33]:
np.all(a>5)

False

In [34]:
# set values with boolean indexing
a[a>5]=0

In [35]:
a

array([1, 2, 3, 4, 5, 0, 5, 4, 3, 2, 1])

In [36]:
a[(a>=3)&(a<=5)] = 0

In [37]:
a

array([1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1])

In [38]:
a =  np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [39]:
np.where(a>5) # returns a tuple of list along for each dimension/axis

(array([5, 6, 7]),)

In [40]:
np.where(a>5)[0]

array([5, 6, 7])

#### Vector Operations

In [41]:
np.array([1,2,5])+np.array([3]) # broadcasted

array([4, 5, 8])

In [42]:
np.array([2,3])**2

array([4, 9])

In [43]:
np.sqrt(np.array([4,9]))

array([2., 3.])

In [44]:
np.exp(np.array([1,2])) # e^array

array([2.71828183, 7.3890561 ])

In [45]:
np.log(np.array([np.e,np.e**2])) # default log is e based

array([1., 2.])

#### Basic stats

In [46]:
a = np.array([1,2,3])

In [47]:
np.max(a)
# a.max() 

3

In [48]:
np.min(a)

1

In [49]:
np.argmax(a)

2

In [50]:
np.sum(a)

6

In [51]:
a.var()

0.6666666666666666

In [52]:
a.std(ddof=1)

1.0

## Matrices and The 2D arrays

In [53]:
a = np.array([
    [1,2,3], #1st row
    [4,5,6]  #2nd row
])

In [54]:
a.shape

(2, 3)

In [55]:
# same way
np.zeros((3,2),int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [56]:
len(a) # gives num of items in first axis
## len(a) == a.shape[0]

2

In [57]:
a.shape[0], a.shape[1]

(2, 3)

In [58]:
np.eye(3,3) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Random Matrix Generation

In [59]:
np.random.randint(0,10,(3,2))

array([[0, 2],
       [3, 5],
       [0, 8]])

In [60]:
np.random.rand(3,2) 

array([[0.65822247, 0.14769196],
       [0.11337981, 0.28844499],
       [0.67508082, 0.03975682]])

In [61]:
np.random.uniform(1,10,(3,2))

array([[5.48934176, 1.53815153],
       [4.48650751, 4.84381209],
       [6.21862434, 4.14396907]])

In [62]:
np.random.randn(3,2) #standard normal: mean 0, std 1

array([[ 2.04586152, -1.3925968 ],
       [-0.25406198, -0.27430643],
       [ 1.64090216, -1.06495594]])

In [63]:
np.random.normal(10,2,(3,2)) # (mean,std,size)

array([[ 8.10744039,  9.14741559],
       [ 9.36841241, 10.3356864 ],
       [ 9.19928053, 11.53817413]])

#### 2D Indexing

In [64]:
a = np.random.randint(1,13,(3,4))
a

array([[ 5,  7,  9,  4],
       [ 3,  2,  5,  9],
       [ 8,  5,  7, 11]])

In [65]:
a[1,2] # [row,col]

5

In [66]:
a[1,:] # 2nd row

array([3, 2, 5, 9])

In [67]:
a[:,2]

array([9, 5, 7])

In [68]:
a[:,1:3]

array([[7, 9],
       [2, 5],
       [5, 7]])

In [69]:
a[-2:,-2:] # last two rows and cols

array([[ 5,  9],
       [ 7, 11]])

In [70]:
a[::2,1::2] # go over all the rows with step 2 but start with col 1 with step 2

array([[ 7,  4],
       [ 5, 11]])

#### The axis argument

In many operations (e.g., sum) you need to tell NumPy if you want to operate across rows or columns. To have a universal notation that works for an arbitrary number of dimensions, NumPy introduces a notion of axis: The value of the axis argument is, as a matter of fact, the number of the index in question: The first index is axis=0, the second one is axis=1, and so on. So in 2D axis=0 is column-wise and axis=1 means row-wise.

Generally speaking, the first dimension i (axis=0) is responsible for indexing the rows, so sum(axis=0) should be read like ***“for any given column sum over all of its rows”*** rather than just “column-wise”. The 2D case is somewhat counter-intuitive: you need to specify the dimension to be eliminated, instead of the remaining one you would normally think about. In higher dimensional cases this is more natural, though: it’d be a burden to enumerate all the remaining dimensions if you only need to sum over a single one.

In [71]:
a = np.array([ 
    [1,2,3],
    [4,5,6]
])

In [72]:
a.sum() # just sums all the elements

21

In [73]:
a.sum(axis=0) # does column-wise summation
# Notice while summing column-wise, the row index changes... THE first index in the shape!

array([5, 7, 9])

In [74]:
a.sum(axis=1)

array([ 6, 15])

***Just remember how Einstein Summation Notation works and you will be good to go***

#### Matrix Arithmetic

In [75]:
a = np.array([
    [1,2],
    [3,4]
])
b = np.array([
    [2,1],
    [1,2]
])

In addition to ordinary operators (like +,-,*,/,// and **) which work element-wise, there’s a @ operator that calculates a matrix product:

In [76]:
a**b # raises power element wise

array([[ 1,  2],
       [ 3, 16]])

#### Broadcasting

In [77]:
a = np.array([ 
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a.shape

(3, 3)

In [78]:
b = np.array([9])
b.shape

(1,)

In [79]:
a+b # b has been broadcasted to match the shape of (3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [80]:
b = np.array([2,2,2])
b.shape

(3,)

In [81]:
a+b # the first index of a and b is same.. so the row of b broadcasted

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [82]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [83]:
b = np.array([
    [2],
    [2],
    [2]
])
b.shape

(3, 1)

In [84]:
a+b # column of b has been broadcasted

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
## Interesting one
a = np.array([1,2,3])
a.shape

(3,)

In [86]:
b = np.array([
    [2],
    [2],
    [2]
])
b.shape

(3, 1)

In [87]:
a+b

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [88]:
## Inner product
a = np.array([1,2,3]) #(3,)
b = np.array([
    [1],
    [2],
    [3]
]) # (3,1)
a@b

# Notice a was interpreted as (1,3) allowing (1,3)*(3,1) inner product

array([14])

In [89]:
### Outer product
## b@a will give shape error
a = a.reshape(1,-1) # making a row vector
b@a # (3,1)@(1,3)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

#### Row vectors and column vectors 

As seen from the example above, in the 2D context, the row and column vectors are treated differently. This contrasts with the usual NumPy practice of having one type of 1D arrays wherever possible (e.g., a[:,j] — the j-th column of a 2D array a— is a 1D array). ***By default 1D arrays are treated as row vectors in 2D operations, so when multiplying a matrix by a row vector, you can use either shape (n,) or (1, n) — the result will be the same.*** If you need a column vector, there are a couple of ways to cook it from a 1D array, but surprisingly transpose is not one of them:

#### Matrix Transpose

In [90]:
a = np.random.randint(1,7,(2,3))
a

array([[6, 1, 5],
       [3, 4, 1]])

In [91]:
a.T

array([[6, 3],
       [1, 4],
       [5, 1]])

In [92]:
b = np.random.randint(1,4,(1,3))
b

array([[2, 1, 2]])

In [93]:
b.shape

(1, 3)

In [94]:
b.T.shape

(3, 1)

In [95]:
### Heres a FUCK YOU!
a = np.array([1,2,3])

In [96]:
a.T

array([1, 2, 3])

????????????????????
So by default trasnpose of (n,) is (n,)!!!!!!!!!

Two operations that are capable of making a 2D column vector out of a 1D array are reshaping and indexing with newaxis

In [97]:
a = np.array([1,2,3,4,5,6])

In [98]:
a.shape

(6,)

In [99]:
# making it a row vector
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [100]:
a.reshape(1,-1).shape

(1, 6)

In [101]:
# OR
a[None,:] # None referes to np.newaxis

array([[1, 2, 3, 4, 5, 6]])

In [102]:
# making it a column vector
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

So, there’s a total of three types of vectors in NumPy: 1D arrays, 2D row vectors, and 2D column vectors. Here’s a diagram of explicit conversions between those:

![alt text](https://miro.medium.com/max/700/1*d9j1sDyzpBXLxK11vU-Mtw.png)

In [103]:
###flatten is always a copy, reshape(-1) is always a view, ravel is a view when possible

a = np.array([[1,2,3,4]])

In [104]:
a.reshape(-1)

array([1, 2, 3, 4])

In [105]:
a.ravel()
# np.ravel(a)

array([1, 2, 3, 4])

In [106]:
a.flatten()

array([1, 2, 3, 4])

##### Matrix Manupulations