For more info go here:
https://www.tensorflow.org/guide/tensor

In [5]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # ignore tf warnings
import tensorflow as tf

#### Initializing Tensors

In [6]:
x = tf.constant(4) # scalar

In [7]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [8]:
# You can specify shape and dtype
x = tf.constant(4, shape=(1,1), dtype=tf.float16)

In [9]:
x

<tf.Tensor: shape=(1, 1), dtype=float16, numpy=array([[4.]], dtype=float16)>

In [10]:
# creating a 2*3 Matrix
x = tf.constant(
    [[1,2,3],
    [4,5,6]]
)

In [11]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [12]:
# just like nupy you can do these
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
tf.eye(3) # identity matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [16]:
tf.random.normal(shape=(2,3),mean=0,stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.565987  ,  1.3283075 , -0.46346048],
       [ 0.16520287, -0.37377703, -0.33365127]], dtype=float32)>

In [17]:
tf.random.uniform(shape=(2,3),minval=0,maxval=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.02849436, 0.29106534, 0.67823946],
       [0.16971064, 0.2619599 , 0.32738245]], dtype=float32)>

In [19]:
x = tf.range(start=1,limit=10,delta=2) #(start,stop,step)

In [20]:
# USE CAST TO CHANGE DTYPES
x = tf.cast(x,dtype=tf.float32)

In [21]:
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 3., 5., 7., 9.], dtype=float32)>

#### Mathematical Operations

In [23]:
x = tf.constant([1,2,3])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [24]:
y = tf.constant([9,8,7])
y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 8, 7], dtype=int32)>

In [25]:
# element wise addition
z = tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [26]:
z = x+y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [27]:
z = tf.subtract(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [28]:
z = tf.divide(x,y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [29]:
z = tf.multiply(x,y)

In [32]:
# DOT PRODUCT
z = tf.tensordot(x,y,axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [34]:
# same thing
z = tf.reduce_sum(x*y,axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [35]:
# Matrix Multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

In [37]:
z = tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.23287898, -0.5426275 ,  1.1554859 ,  2.1808853 ],
       [-0.85096884,  0.84309137, -1.2135061 ,  1.1249032 ]],
      dtype=float32)>

In [38]:
z = x@y 
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.23287898, -0.5426275 ,  1.1554859 ,  2.1808853 ],
       [-0.85096884,  0.84309137, -1.2135061 ,  1.1249032 ]],
      dtype=float32)>

#### Indexing Tensors

In [39]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9])

In [40]:
x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [41]:
x[1:]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [42]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [43]:
x[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [44]:
x[::-1] # reverse order

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [45]:
# You can GATHER elements by their indices
indices = tf.constant([0,3]) # list all the indices
x_ind = tf.gather(x,indices) # select all the given indices
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>

In [46]:
x = tf.constant([[1,2],[3,4],[5,6]])

In [49]:
# while slicing just remember, just like numpy dimensions are seperated by commas
x[0,:] # get the 1st rows' all the columns

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [51]:
# Get the first two rows
x[0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Reshaping

In [52]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [54]:
x = tf.reshape(x,shape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [55]:
# Transpose
x = tf.transpose(x)
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>